name: Makefile CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  workflow_dispatch: # Manually trigger a workflow run

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: make all

      - name: Release with build artifact
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/baash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
