name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build Project
      run: make all

    - name: Create a Release
      uses: elgohr/Github-Release-Action@v5
      with:
        title: MyReleaseMessage
