name: Makefile CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: make all

      - name: Release with build artifact
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
